SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE AUTHORITY
(
	-- 登録されたSQLを識別するID
	SQL_ID INT NOT NULL COMMENT '登録されたSQLを識別するID',
	USER_ID INT NOT NULL,
	-- 0 　権限なし
	-- 1    実行権限権限のみ
	-- 2    実行権限と編集権限
	AUTH_LEVEL INT COMMENT '0 　権限なし
1    実行権限権限のみ
2    実行権限と編集権限',
	PRIMARY KEY (SQL_ID, USER_ID),
	UNIQUE (SQL_ID)
);


CREATE TABLE CI_SESSIONS
(
	SESSION_ID VARCHAR(40) DEFAULT '0' NOT NULL,
	IP_ADDRESS VARCHAR(16) DEFAULT '0' NOT NULL,
	USER_AGENT VARCHAR(150) NOT NULL,
	LAST_ACTIVITY DATETIME DEFAULT '0' NOT NULL,
	USER_DATA TEXT NOT NULL,
	PRIMARY KEY (SESSION_ID)
);


CREATE TABLE DBINFO
(
	-- データベースID。DB情報を一位に決定するもの
	DB_ID INT NOT NULL COMMENT 'データベースID。DB情報を一位に決定するもの',
	DISPLAY_NAME VARCHAR(30),
	-- DB製品名（mysql/mssql)
	DBMS VARCHAR(30) COMMENT 'DB製品名（mysql/mssql)',
	-- データベースのホスト名 or IP
	DB_HOST VARCHAR(30) COMMENT 'データベースのホスト名 or IP',
	-- DB接続用ユーザー
	DB_USER VARCHAR(30) COMMENT 'DB接続用ユーザー',
	-- DB接続用のパスワード
	DB_PASSWD VARCHAR(30) COMMENT 'DB接続用のパスワード',
	DB_NAME VARCHAR(30),
	PRIMARY KEY (DB_ID)
);


CREATE TABLE LOGIN_ATTEMPTS
(
	ID INT NOT NULL AUTO_INCREMENT,
	IP_ADDRESS VARCHAR(40) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL,
	TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE SQL_INFO
(
	SQL_ID INT NOT NULL,
	-- データベースID。DB情報を一位に決定するもの
	DB_ID INT NOT NULL COMMENT 'データベースID。DB情報を一位に決定するもの',
	-- 分類（KH/KD/KC/AT/EK/WPDなど）
	CATEGORY VARCHAR(30) COMMENT '分類（KH/KD/KC/AT/EK/WPDなど）',
	-- SQLの名前
	SQL_NAME VARCHAR(200) COMMENT 'SQLの名前',
	-- SQLの説明
	DESCRIPTION TEXT COMMENT 'SQLの説明',
	SQL_TEXT TEXT,
	PRIMARY KEY (SQL_ID)
);


CREATE TABLE USERS
(
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	ACTIVATED BOOLEAN DEFAULT '49' NOT NULL,
	BANNED BOOLEAN DEFAULT '48' NOT NULL,
	BAN_REASON VARCHAR(255),
	NEW_PASSWORD_KEY VARCHAR(50),
	NEW_PASSWORD_REQUESTED DATETIME,
	NEW_EMAIL VARCHAR(100),
	NEW_EMAIL_KEY VARCHAR(50),
	LAST_IP VARCHAR(40) NOT NULL,
	LAST_LOGIN DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL,
	CREATED DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL,
	MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE USER_AUTOLOGIN
(
	KEY_ID CHAR(32) NOT NULL,
	USER_ID INT DEFAULT 0 NOT NULL,
	USER_AGENT VARCHAR(150) NOT NULL,
	LAST_IP VARCHAR(40) NOT NULL,
	LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (KEY_ID, USER_ID)
);


CREATE TABLE USER_PROFILES
(
	ID INT NOT NULL AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	COUNTRY VARCHAR(20),
	WEBSITE VARCHAR(255),
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE SQL_INFO
	ADD FOREIGN KEY (DB_ID)
	REFERENCES DBINFO (DB_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AUTHORITY
	ADD FOREIGN KEY (SQL_ID)
	REFERENCES SQL_INFO (SQL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AUTHORITY
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



